// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqj6stKH3RfKSdBTqats41qxqlfdX9q1M',
    appId: '1:101585356667:web:dde64ca26cd79bb99ddfde',
    messagingSenderId: '101585356667',
    projectId: 'study-app-a3845',
    authDomain: 'study-app-a3845.firebaseapp.com',
    storageBucket: 'study-app-a3845.appspot.com',
    measurementId: 'G-Q5FX2WZHNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHU3G1vKGL_I4xiINzvMKwXQYWrUQOvek',
    appId: '1:101585356667:android:43e229cd8ed25e859ddfde',
    messagingSenderId: '101585356667',
    projectId: 'study-app-a3845',
    storageBucket: 'study-app-a3845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUTke1G6QSO9auwlGi6dPcTqBMys8Ykm4',
    appId: '1:101585356667:ios:f7f34fad7dd3acd39ddfde',
    messagingSenderId: '101585356667',
    projectId: 'study-app-a3845',
    storageBucket: 'study-app-a3845.appspot.com',
    androidClientId: '101585356667-cnl952qdfv4n0uocifd4947f9ooa1v59.apps.googleusercontent.com',
    iosClientId: '101585356667-4c3d55rme0m3cvo8939b11hfo0ekgouq.apps.googleusercontent.com',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUTke1G6QSO9auwlGi6dPcTqBMys8Ykm4',
    appId: '1:101585356667:ios:29fc19e0017f853f9ddfde',
    messagingSenderId: '101585356667',
    projectId: 'study-app-a3845',
    storageBucket: 'study-app-a3845.appspot.com',
    androidClientId: '101585356667-cnl952qdfv4n0uocifd4947f9ooa1v59.apps.googleusercontent.com',
    iosClientId: '101585356667-0uvaqa2uf26kjkgjq7c761l9qmvrgo12.apps.googleusercontent.com',
    iosBundleId: 'com.example.study.RunnerTests',
  );
}
